name: build-fix-and-feature-branches

on:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['spring-boot-3,examples', 'spring-boot-2']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: m2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile
        run: ./mvnw clean test-compile

      - name: Verify
        run: ./mvnw verify -P "${{ matrix.profile }}"
